name: ci

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/gallium", "lts/hydrogen", "current"]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node 🧰
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies 🗂
        run: npm ci

      - name: Build 🛠
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run build --if-present

      - name: Test 🔧
        run: npm run test
  lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node 🧰
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies 🗂
        run: npm ci

      - name: Lint 💄
        run: npm run lint
